### PR TITLE
[WIP] Distinguish science colors from each other. Attempt to match SE scien…

### PR DESCRIPTION
**Pull request by MarximusMaximus**
…ce colors somewhat.

Bright and dark science pairs (chemical changed to cyan, logistics changed to orange)
image

Green and dark green for biological to match SE:
image

### CODE REVIEW

**Comment by Dysoch** [comment]
I will think about this for now. The color scheme is now a bit weird

**Comment by MarximusMaximus** [comment]
Yea. I'm not totally thrilled with it either, but SE uses green for biological, so I tried to match that, which left me with swapping in the orange (Material Science) color for logistics (it was difficulty having 4 different types the same color). As for the blue, it was just looking very dark and hard to distinguish from actual black on my one screen, so I bumped up the brightness and ended up with cyan. Mostly it was just difficult to distinguish between regular and advanced on the tech screens.

**Comment by MarximusMaximus** [comment]
I think SE gets around this by using multiple shades of blue on their Astronomic Science items from the solid black on the Deep Space Science item.

**Comment by MarximusMaximus** [comment]
An alternative idea would be to go with maybe something like this instead of programmatic colors:
https://mods.factorio.com/mod/cb-science
(note: can't use these icons directly b/c of the mod's license, although making it a required dependency would probably work; but better to create new ones in the same kind of "idea" as this)

Another alternative would be to stick with the original game icons but make the advanced ones have an overlay icon like the inserters?

**Comment by Myricaulus** [comment]
Ever though about using anything else then a erlenmeyer flask as a shape? Chemist use a variety of different flasks, would be even easier to distinguish and also maybe teach somebody a bit about chemistry.

**Comment by MarximusMaximus** [comment]
@Myricaulus That'd be cool, but I'm not an artist! Also, when the liquid science is in pipes, it should be differentiable, no?

**Comment by heinwessels** [comment]
Another option is to combine the science packs with other icons, like Nullius does it. Each science pack can effectively have _two_ colours defining it instead of the single tint you're currently applying. Best examples is the red science with a grey hear (I think) or the white science with a red nuclear symbol.

An example of the Nullius science packs:


Just a thought. It's a hard problem you're tackling :)

**Comment by MarximusMaximus** [comment]
Yea, the icons are actually somewhat easier to deal with than the fluid colors. :-/

**Comment by Dysoch** [comment]
I have an idea for this after i digged through my old files. i have seperate sprites for the advanced ones that can come in handy here

**Pull request closed without merging**
